[package]
name = "rust-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
hyper = "0.14"
tower = "0.4"
serde = {version ="1.0.217", features=["derive"]}

[dev-dependencies]
anyhow= "1"
httpc-test = "0.1.2"
